# Generated by Django 4.0.5 on 2022-07-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='vop1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='vop2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='vop3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='vop4',
            field=models.IntegerField(default=0),
        ),
    ]
