# Generated by Django 4.0.5 on 2023-08-19 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0003_remove_question_op0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polling.user'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='Q_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polling.question'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polling.user'),
        ),
    ]
