# Generated by Django 4.0.5 on 2023-08-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0004_alter_question_user_id_alter_votes_q_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='votes',
            name='Q_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='votes',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
